FAKE_PROFILE = {
    "name": "Nordic Bistro",
    "address": "Mannerheimintie 1, 00100 Helsinki",
    "rating": 4.6,
    "review_count": 542,
    "price_level": "€€",
    "category": "Modern European Restaurant",
    "description": "A modern bistro in the heart of Helsinki.",
    "hours": ["Mon-Fri 11:00–22:00", "Sat 12:00–00:00", "Sun 12:00–21:00"],
    "menu_url": "https://www.nordicbistro.fi/menu/",
    "website": "https://www.nordicbistro.fi/",
    "photos": [],
    "profile_completeness": 92,
    "photo_count": 24,
    "recent_reviews": 18,
    "last_profile_update": "2024-06-01",
    "menu_available": True,
    "gamification": {
        "score": 87,
        "badges": [
            {"name": "Photo Pro", "description": "Uploaded 20+ photos"},
            {"name": "Review Magnet", "description": "500+ reviews"}
        ]
    },
    "localTrends": [
        "Customers are searching for: Summer terrace, vegan brunch, local ingredients",
        "High interest in chef's tasting menus and dessert samplers.",
        "If this were not mock data: These trends would be generated by analyzing recent search queries, customer reviews, and competitor activity in your area, possibly using AI or analytics services."
    ],
    "photoInsights": [
        "Most photos are of main courses; add more ambience and staff photos.",
        "Outdoor seating photos are underrepresented.",
        "Competitors have more photos of group events and celebrations.",
        "If this were not mock data: These insights would be generated by analyzing your uploaded business photos and comparing them to those of competitors, using image recognition and business analytics."
    ],
    "competitorAlerts": [
        "Urban Eatery just added 10 new photos.",
        "Bistro Helsinki is running a summer terrace campaign.",
        "A new vegan cafe opened 200m away.",
        "If this were not mock data: These alerts would be generated by monitoring competitor activity (e.g., new photos, campaigns, menu changes) via APIs, web scraping, or business intelligence tools."
    ]
}
